### ISSUE TITLE
Running drucker on mac os elcapitan can't connect to images over ssh

### ISSUE THREAD

**Issue by eporama** [anavarre/drucker#6] opened 2016-07-29 19:26 UTC
while running the drucker setup script we get:

```
Running drucker_base orchestration on the container...

PLAY [drucker_base] ************************************************************

TASK [setup] *******************************************************************
fatal: [203.0.113.99]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    to retry, use: --limit @/Users/erik.peterson/src/drucker/orchestration/base.retry

PLAY RECAP *********************************************************************
203.0.113.99               : ok=0    changed=0    unreachable=1    failed=0

```

for all of the containers that it tries to spin up. 

You can run

```
docker exec -it drucker_web bash
```

to connect, but it doesn't appear that any of the ansible scripts have run, so none of the services are up.

**Comment by anavarre** [comment] 2016-08-03 10:02
Sorry for the response lag. I'm currently OOO with mobile only. Will expand by EOW.

Sanity check: have you followed those steps? 

> Add the below in your config file (under $HOME/.ssh) or create the file if it doesn't exist.
> 
> Host 203.0.113.99 203.0.113.2 203.0.113.10 203.0.113.11
>   StrictHostKeyChecking no
>   UserKnownHostsFile=/dev/null
>   LogLevel=error
> 
> This will prevent SSH strict host key checking from getting in the way, since drucker is for development purposes only.

**Comment by anavarre** [comment] 2016-08-05 11:26
Back with my laptop, I just tried commenting out the above `.ssh/config` code and got the following:

```
$ drucker
Custom drucker bridge network already exists.
drucker:base image already exists.
drucker_reverse_proxy container already exists.
Running drucker_reverse_proxy orchestration on the container...

PLAY [drucker_reverse_proxy] ***************************************************

TASK [setup] *******************************************************************
fatal: [203.0.113.2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

PLAY RECAP *********************************************************************
203.0.113.2                : ok=0    changed=0    unreachable=1    failed=0
```

Note: the output is slightly different to yours because my containers have already been successfully spun up. Reproducing the issue does look fairly identical though.

Since Ansible needs a valid SSH keypair (and in drucker's case, a `config` file, too), this would be the first thing I'd double check.

**Comment by anavarre** [comment] 2016-08-30 12:14
Closing. Please re-open if you need more assistance.

**Closed as completed by anavarre** 2016-08-30 12:14 UTC
Labels: support
